import 'leaflet/dist/leaflet.css'
import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import 'leaflet/dist/leaflet.css';
// import { Google_Sans } from 'next/font/google';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const geistRoboto = Roboto({
  variable : '--font-roboto',
  subsets : ['latin'],
  weight: ['100','200','300','500','600','700','800','900'],
})

// const googleSans = Google_Sans({
//   variable: '--font-googlesans',
//   subsets: ['latin'],
//   weight: ['400','700'],
//   display: 'swap'
// })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          src={`https://maps.googleapis.com/maps/api/js?key=${process.env.GOOGLE_MAPS_PLATFORM_API_KEY}&libraries=places`}
          async
          defer
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} ${geistRoboto.variable}`}>
        {children}
      </body>
    </html>
  );
}
